"""Regenerate README.md's "Headline number" and "Known gaps" numbers from
the current cze build.

Run after the cze pipeline is up to date (`make all` / `NATION=cze uv run
python -m src.render`):

    uv run python scripts/readme_numbers.py

It reads only `data/processed/cze/{per_capita.parquet, pool.parquet,
data_quality.json, features_*.parquet}` (plus `config/seasons.yaml` for the
metrics-season label, read via `src.config`) and prints two blocks to
stdout. Paste the output into README.md's corresponding sections and update
the "generated by scripts/readme_numbers.py on <date>" stamp there --
nothing here writes the README itself, so a stale paste is visible in the
date rather than silently wrong.
"""

from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

import pandas as pd

from src import config
from src.utils import season_label

ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT_DIR / "data" / "processed" / "cze"
GROUPS = ("FW", "MF", "DF")

_ORDINAL_SUFFIX = {1: "st", 2: "nd", 3: "rd"}


def _ordinal(n: int) -> str:
    if 11 <= n % 100 <= 13:
        return f"{n}th"
    return f"{n}{_ORDINAL_SUFFIX.get(n % 10, 'th')}"


def load() -> tuple[pd.DataFrame, pd.DataFrame, dict, dict[str, pd.DataFrame]]:
    per_capita = pd.read_parquet(DATA_DIR / "per_capita.parquet")
    pool = pd.read_parquet(DATA_DIR / "pool.parquet")
    data_quality = json.loads((DATA_DIR / "data_quality.json").read_text(encoding="utf-8"))
    features = {g: pd.read_parquet(DATA_DIR / f"features_{g}.parquet") for g in GROUPS}
    return per_capita, pool, data_quality, features


def headline_block(per_capita: pd.DataFrame) -> str:
    ranked = per_capita.sort_values("per_million", ascending=False).reset_index(drop=True)
    cze = per_capita[per_capita["country"] == "CZE"].iloc[0]
    rank = int(cze["rank"])
    n_peers = int(len(per_capita))
    n_players = int(cze["n_players"])
    ranking = ", ".join(
        (f"**Czechia {r['per_million']:.2f}**" if r["country"] == "CZE" else f"{r['name']} {r['per_million']:.2f}")
        for _, r in ranked.iterrows()
    )
    return (
        f"**{cze['per_million']:.2f}** top-9-league players per million inhabitants -- "
        f"{n_players} Czech players on the current rosters of Europe's nine strongest leagues "
        f"(headline top-9), divided by a 2024 Eurostat population estimate of {cze['population_m']:.1f} M. "
        f"That ranks Czechia {_ordinal(rank)} of {n_peers} peer countries: {ranking}."
    )


def known_gaps_block(pool: pd.DataFrame, data_quality: dict, features: dict[str, pd.DataFrame]) -> str:
    seasons = config.seasons()
    metrics_season = seasons["metrics"]
    n_pool = int(len(pool))

    checks = {c["id"]: c for c in data_quality.get("checks", [])}
    no_tables_check = checks.get("no_tables")
    n_no_tables = int(no_tables_check["count"]) if no_tables_check else int((~pool["in_fbref_tables"]).sum())

    def _metrics_rows(df: pd.DataFrame) -> pd.DataFrame:
        # One row per player in the metrics season, the club with most minutes
        # (a mid-season transfer otherwise counts twice) -- mirrors
        # src.render._metrics_rows.
        cur = df[df["season"] == metrics_season]
        return cur.sort_values("min", ascending=False).drop_duplicates("player_key")

    eligible = {g: _metrics_rows(df)[lambda d: d["home_eligible"]] for g, df in features.items()}
    n_with_metrics = int(sum(len(df) for df in eligible.values()))
    n_nt_flagged = int(sum(int(df["nt_flag"].sum()) for df in eligible.values()))

    lines = [
        f"- **Leagues without metrics.** {n_no_tables} of the {n_pool} Czech professionals found on "
        "FBref's country page play in a league without season tables and carry no metrics; they are "
        "listed by name and club only.",
        f"- **National-team flag source.** {n_nt_flagged} of the {n_with_metrics} mapped players "
        f"(season {season_label(metrics_season)}) carry the \"called up\" flag.",
        f"- **Mapped players with metrics.** {n_with_metrics} of the {n_pool} pool players have a "
        f"complete {season_label(metrics_season)} season (>= the report's minutes floor) in a "
        "fetched league.",
    ]
    return "\n".join(lines)


def main() -> None:
    per_capita, pool, data_quality, features = load()
    today = dt.date.today().isoformat()
    print(f"<!-- generated by scripts/readme_numbers.py on {today} -->")
    print()
    print("## Headline number")
    print()
    print(headline_block(per_capita))
    print()
    print("## Known gaps (computed numbers)")
    print()
    print(known_gaps_block(pool, data_quality, features))


if __name__ == "__main__":
    main()
